// global variables for admonition icons 
:tip-caption: pass:[<span style="font-size: em">TIP 💡</span]
:note-caption: pass:[<span style="font-size: em">  NOTE ✏️ </span]
:important-caption: pass:[<span style="font-size: em"> IMPORTANT ❗ </span]

// document Title 
= Containerization: A Simplified Approach for Accessing Computational Software on Your Mac
:toc:
Dylan Torres <dylan.l.torres@ucdenver.edu>

== Computational Software: The Good and the Bad
The flow of water is mesmerizing. Since performing my first fluid dynamics simulation, everyday experiences such as a gust of wind or the trickling of a creek have taken on new meaning.  

Whether you're intersested in engineering, biology, physics or chemistry, working with computational software has the potential to foster growth in areas where pure theory and math may fall short.  

The issue is that most computational software packages are developed for Linux, making them difficult to install - especially for those of us who lack experience with the the Unix shell.  Fortuantely, a process called containerization has made accessing computational software a whole lot easier.

With the use of a containerization platform called Docker, I recently installed a molecular dynamics (MD) package called http://ambermd.org[Amber] on my Mac.  I'll show you how to do the same and hopefully you'll be conducting MD
simulations at the no time!

TIP: If you have little to no experience using the Unix Shell, check out this http://swcarpentry.github.io/shell-novice/[tutorial].  

== Docker Desktop for Mac
Before we run any molecular dynamics simulations, we have to install Docker. The latest version is called *Docker Desktop*. Does your mac satisfy the system requirements?

=== System Requirements for Mac
=====
. Mac hardware must be a 2010 or new model. You can check to see if your machine is supported by entering the following input and receving the following output in the Terminal:
+
```sh
$ sysctl kern.hv_support
kern.hv_support: 1
```
 . macOS Sierra 10.12 and new releases are supported (new versions recommended).
 . Must have at least 4 GB of RAM
 . If you have the virtual machine software, VirtualBox installed on your computer, it can get in the way of successfully installing  Docker. As long as it's later than version 4.3.30, it should be fine. If you don't have it, even better! 

NOTE: If your system does not meet the requirements, it's possible that an older version of Docker called https://docs.docker.com/toolbox/overview/[Docker Toolbox] can be installed on your Mac. Keep in mind that the older version wasn't tested for these instructions. 
=====



=== Install Docker Desktop for Mac
=====
[NOTE]
.File Extensions
====
`.dmg` files or, Apple Disk Image Files, are typically used to compress software installers. DMGs are "mounted" as drives and treated by the OS as if they are physical hard drives, making it easy to view their content and install. 
====
. Download https://download.docker.com/mac/stable/Docker.dmg[Docker Desktop].
. Double-click `Docker.dmg` to open the installer, then drag the whale to the Applications folder.
// IMAGE::EXAMPLE2
. Double-click Docker.app in the Applications folder to start Docker. You can easily locate files on your computer using the spotlight search. 
+
. Authorize `Docker.app` with your system password after Docker is launched.
+
//6
//7
. A new windown will appear prompting you to create a DockerHub account. Create an account.  
+
//8
Notice the little whale icon in your task bar. As an application, Docker primarily runs in the  background, only accessible through the Terminal. Click on the icon when you want quit running Docker. 
//9

[IMPORTANT]
.*System Preferences*
Apple has mac OS set up so that unless applications aren't downloaded from the AppStore, you'll have to manually grant access. The following  window may appear:
//IMAGE::3

. OPEN the system preferences. Click on the grid icon in the upper left corner of the window, and select the  Security and Privacy icon. Under the general tab, in the bottom left corner of the window, click the lock icon to make changes. 
//4
+
.Then click Open Anyway
//5
+
. (again) Another window will appear asking if you want to open an App not download form the AppStore.
+
. Click open
=====

== Setting Up
=====
[NOTE]
.File Extensions
====
`.tar` files store multiple files in one and are primarily used to archive in Linux/Unix systems. 

`.bz2` files are used to compress TAR files (and others) for quick and easy software distribution. 
====
. *Download Amber*
+
====
* *AmberTools18 (Open Source)*
** Download http://ambermd.org/GetAmber.php#ambertools[AmberTools18]. The recommended download method is *Option 1: Getting the Source Code*. 
Fill out the required fields to get the `AmberTools18.tar.bz2`. 
// image
* *Amber18 Source Code (License Required)*
** After purchasing a license (or obtaining one from school/work) for http://ambermd.org/GetAmber.php#ambertools[Amber18], follow the `Amber18.tar.bz2` download instructions sent to you. 
====
. *Download VMD 1.9.3*
+
====
* Download https://www.ks.uiuc.edu/Research/vmd/vmd-1.9.3[VMD-1.9.3] (linux-OpenGL Version]
into the  `/AmberDocker` directory and rename it `vmd-1.9.3-tar.gz`.
====
. *Download Real VNC*
+
====
* Download https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.19.325-MacOSX-x86_64.dmg[VNC Viewer]. This will provide us with an https://en.wikipedia.org/wiki/Ubuntu[Ubuntu] graphical user interface (GUI) to interact with the container. 
=====

== Building Your Own Molecular Dynamics Container

Now that everything is setup, lets a better idea of _what_ containers are, and _how_ they're useful by running your own container capable of running MD simulations with Amber. 

=== What _are_ Containers and _How_ Are They Useful?

==== Containers Are Neatly Packed Units of Software That Run The Linux Kernel

THE PROBLEM:

Many of the Computing Software Programs available today were developed for Linux-based operating systems (the Linux Kernel). Incompatabilities between the Linux Kernel and Apple's XNU kernel prevent Linux-based software from runnig on macOS. 
======
THE SOLUTION:

Containers run Linux-based operating systems on your computer separate from macOS.  


In the terminal,type: 
```sh
  $ docker --version
```
You should receive an output similar to this: 

```sh
  Client: Docker Engine - Community
   Version:           18.09.2
   API version:       1.39
   Go version:        go1.10.8
   Git commit:        6247962
   Built:             Sun Feb 10 04:12:39 2019
   OS/Arch:           darwin/amd64
   Experimental:      false

 Server: Docker Engine - Community
  Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Docker uses a *client-server* infrstructure. You are the Client and the Server is called the *Docker Damien*. 

Notice both rows labeled `OS\Arch:`: 

.`darwin/amd64`: ==
Darwin is is an open-source operating system that forms a primary componeent of macOS. Both of these are layer on top of the XNU kernel. 

.`linux/amd64`:
linux indicates that the system is built upon the Linux kernel. 

Fun Fact: the word daemon comes from ancient Greek belief of a supernatural being that lives in the background with with no particular bias toward good or evil.
======

=== Computing Software Pakages are Massive
====
.THE PROBLEM: 

CSPs have lots of dependencies and may require installed compilers.

.THE SOLUTION:
. The dependencies and compilers of an application aren't installed on your hard drive - they're packaged in the container which is hosted by the Docker Daemon. 
. Containers keep the source code, dependencies and compilers of an application neatly packaged and modular. 
. Running applications in containers doesn't slow down your computer (it uses the Daemon server to run applications). 
====

As users, we rely on  built-in libraries called *dependencies*. These libraries are how we instruct the computer to perform simulations. But before any simulations take place, we have to *compile*  our code from a human readable format to a machine-readable format, also known as a *compiiled exectuable* .   


So, CSPs require *dependencies* and *compilers* to successfully run on a system. Higher capabilities of a CSP to perform various tasks typically means that larger sets of dependencies and compilers will be required. 


== Building Your Docker Image 

A Docker *container image* (simply referred to as an _image_) is a lightweight, standalone, executable package of sotware that includes everything needed to run an application: code, runtime, system tools, system libraries and settings. 

First, we need to download the necessary files to build the  image:

```sh
$ git clone https://github.com/yylonly/AmberDocker.git
```

Now, use `ls` to list the files in your current directory. You should find a new directory named `AmberDocker`. Change to that directory with `cd`.

```sh 
$ ls
AmberDocker
$ cd AmberDocker
AmberDocker $
```

Another `ls` will reveal several files:
```sh
$ ls
README.md	 Dockerfile		src     	
```

****
[NOTE]
.File Extensions
====
The file `README.md` contains instructions for you, the user on how to ensure the image is properly built. `.md` indicates it was written using a text editor called MarkDown. 


The `Dockerfile` contains the instructions for the Docker daemon to build the image. 

`src` is a type of directory used in Unix OS that contain source code. 
====
****

Now, let's open up that `README.md` file:

```sh
$ open README.md
```

****
NOTE: You'll need a text editor to view a `.md` file. You can also view it https://github.com/yylonly/AmberDocker/blob/master/README.md[here]. However, as you become more experienced, you'll benefit from having a text editor like https://code.visualstudio.comhttps://code.visualstudio.com[Visual Studio Code].
****

After opening `README.md`, you can see that we already have most of what we need to build our image. All that's left is to download https://www.ks.uiuc.edu/Research/vmd/vmd-1.9.3/[VMD-1.9.3(linux-OpenGL Version)].

After downloading, rename the file to `vmd-1.9.3.tar.gz`.

Okay, now move the following files to the AmberDocker directory:

* `AmberTools18.tar.bz2`
* `Amber18.tar.bz2` 
* `vmd-1.9.3.tar.gz`

into the  `/AmberDocker` directory and rename it `vmd-1.9.3-tar.gz`.

FINALLY, it's time to *build the image*! In the AmberDocker directory:

```sh
$ docker build . -t amber18:cpu
```

****
[NOTE]
.Docker Build Command: Build an Image
====
```sh
docker build [OPTIONS] PATH | URL | -
```
we used `.`  as the `[PATH]` to build the image in the current `/AmberDocker` directory

`-t` or `--tag list` is an `[OPTION]` that we used to name the container `amber18:cpu`
====
****

Once the image is built, we can search for it by the tag name. 

This process takes about an hour while the Docker client connects to the Docker Daemon to build our image. 


= Before Running a Container, We Have to Build an Image




By packaging source code, dependencies, and compilers in a *container*,  we use a network. This means that bulky CSPs just got a whole lot lighter.

Just to give you an idea:
 
// INSERT IMAGE::EXAMPLE1


The way this works is by running a *Dockerfile*. A Dockerfile contains the instructions for *executable* files to be *compiled* within a container. 





is an open-source platform that runs applications on a computer's operating system by packaging all the dependencies and executables of Amber in a  _container_, we can run molecular dynamics simulations without overloading the Mac OS. 




=== Getting Familiar with Docker

 
The command `docker` allows you to call on the *docker client*. The Docker client docker client communicates with the *engine* of the Docker platform - also known as the *Docker damien*.   

In multitasking computer operating systems a daemon runs as a background process rather than under direct control of an interactive user. 
=== The Docker Command Line

====
NOTE: The required syntax for executing any Docker command is `docker [OPTIONS] COMMAND [ARG...]`.
====

Everytime you use Docker, you have to call on the Docker client. You can't run Docker without it! 

****
You'll mostly use the Docker client to:
====
. Build Images: `docker build`
. Run Containers: `docker run`
. Setup networking for containers
. Manage disk volumes for the container   
====
****

In the Terminal, run `docker` and you'll get a list 
of available *commands*, *options* and descriptions on how to use them.  

```sh 
$ docker
Usage: docker [OPTIONS] COMMAND [ARG...]
       docker [ --help | -v | --version ]

A self-sufficient runtime for containers.

Options:
      --config string      Location of client config files (default "/root/.docker")
  -D, --debug              Enable debug mode
      --help               Print usage
  -H, --host value         Daemon socket(s) to connect to (default [])
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Commands:
    attach    Attach to a running container
    # […]
```




== Running Your Docker Container

A Docker *container* runs an application by packaging all the code and dependencies packaged up neatly so the application runs quickly and reliably. 

It doesn't matter that Amber wasn't written specifically for macOS because the way we have things set up, Amber will run using an operating system within the container! This works by tapping into the network hosted by the Docker daemon.



==== Docker Images Become Containers
To run our image in a countainer, we need to use the `docker run` command. But first, let's check out that `README.md` document again.

According to the instructions, we need to download and install an application called https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.19.325-MacOSX-x86_64.dmg[VNC Viewer]. This will provide us with an https://en.wikipedia.org/wiki/Ubuntu[Ubuntu] graphical user interface (GUI) to interact with the container. 

The time has finally come.... let's run our container! In the `/AmberDocker` directory:
```sh
$ docker run --rm -p 5901:5901 -p 6901:6901 -v $(pwd):/data --user 0 amber18:cpu
```


****
[NOTE]
.Docker Run Command: Run an Image in a Container
====
```sh
docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
```

`-rm` Automatically removes the container after it is exited. 

`-p` Pubishes all ports to random ports

`-v` Mounts volumes from the specified container

`--user` User namespace to use
====
****


Open a new terminal window and enter the `ps` (process status) command. This shows containers that are currently running:
```sh
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
c2598f1332ab        amber18:cpu         "/dockerstartup/vnc_…"   10 seconds ago      Up 8 seconds        5901/tcp, 6901/tcp   eloquent_nobel
```

notice the output:

`CONTAINER ID`: an alphanumeric sequence assigned to the container

`IMAGE`: the tag we assigned to the image

This is great, to run the container from now on, all we have to type is:

```sh
$ docker run amber18:cpu
```

To stop the container:
```sh
$ docker stop [CONTAINER ID]
```

==== Connect to the Container

. Open the VNC viewer.
+ 
+
. Access the container (password: `vncpassword`).
+
* Via the VNC application: 127.0.0.1:5901

* Via the web: http://127.0.0.1:6901/vnc.html


=


== Resources and Troubleshooting
=== Docker

For help with any Docker command, execute the command in question followed by the `--help` option. For example:
```s
$ docker run --help

Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

Options:
      --add-host value             Add a custom host-to-IP mapping (host:ip) (default [])
  -a, --attach value               Attach to STDIN, STDOUT or STDERR (default [])
...
```

****
[TIP]
.Docker Resources
====
* For in-depth descriptions and examples, access the https://docs.docker.com/reference/[ Docker Refrence Documentaiton] page.
* For practice, Aqua Container Security compiled a list of https://www.aquasec.com/wiki/display/containers/100+Best+Docker+Tutorials["The Best 100 Docker Tutorials"]. 
====
****

---
 






== Molecular Dynamics: Amber

Since its creation in the late 1970s, Amber has gone from using just two languages (Fortran and C) to using Python, Cuda and Pearl with over 850,000 lines of code.This growth forced developers to divide the package into two platforms with the current versions being: *AmberTools18* and *Amber18*.

====
NOTE: You can always compare your version of Docker to the latest version by looking at https://docs.docker.com/docker-for-mac/release-notes/[Docker release notes]. 
====
