// global variables for admonition icons 

:important-caption: pass:[<span style="font-size: em">IMPORTANT ❗</span]

:note-caption: pass:[<span style="font-size: em">NOTE ✏️</span]

= Installing Amber18 with Docker
Dylan Torres <dylan.l.torres@ucdenver.edu>  

Most applications and software downloaded from the web require just a few clicks of a mouse to be successfully installed on a computer. Amber, a Linux-based application, is not so simple.

Difficulties of the installation process are heightened for Mac and Windows users, requiring the use of integrated development environments and programs that translate source code into machine readable code called compilers. 

From these instructions, you will learn a simpler and faster way of installing Amber on your Mac or PC with the use of a tool called Docker. 

== What is Amber, exactly?

Amber is a set of Linux-based programs that simulate how particles and molecules interact and behave. Amber is offered in two parts: AmberTools18 and Amber18. By the end of this document, you will (hopefully) have both  parts installed and running on your computer. 


== What is Docker?
Docker is a tool that simplifies the installation and running of Linux-based applications across different operating systems.

Rather than running Amber on your computer's operating system, Docker builds an *image* which allows you to operate Linux in a *container*, allowing Amber to run separately from your computer's operating system.

=== Docker Images

A Docker image is a file that contains instructions for your computer to install and run applications in a container. 

=== Docker Containers

A Docker container is where the application actually runs. The container contains the Docker image, the files for the application you wish to run and the Linux operating system. 

[IMPORTANT]

.Docker System Requirements
====

Mac: 

 . Mac hardware must be a 2010 or new model.
 . macOS Sierra 10.12 and new releases are supported (new versions recommended).
 . Must have at least 5 GB of RAM
 . If VirtualBox is installed on yor computer, the version must be LATER than version 4.3.30
====



== Installation Instructions: AmberTools18 and Amber18

=== Requirements 
. gitHub account
. Docker 
. AmberTools18 andAmber18 source code
. VNC Viewer

==== Create a gitHub Account
To create a gitHub account, click https://github.com[here]. 

==== Download and install Docker 
Download Docker from https://hub.docker.com/editions/community/docker-ce-desktop-mac[here]. Follow the download and installation instructions.

==== Download Amber 
. Download AmberTools18 and Amber18 from your source.

==== Download a Virtual Newtork Computing (VNC) viewer
The Docker container taps into a nework host that contains Linux. The VNC transmits the graphics from the host pixel by pixel, displaying a Linux graphical user interface (GUI) in the container just as your operating system displays a (GUI) on your monitor. 

. Download RealVNC from https://www.realvnc.com/en/connect/download/viewer/[here] but DO NOT install.
. Rename the file to vmd-1.9.3.tar.gz .


=== Build the Amber Docker image
//- 
. In the terminal, move to the directory in which you would like to build the container.
. Clone the Amber Docker Files from gitHub.
+
 git clone https://github.com/yylonly/AmberDocker.git    
 
+
NOTE: There should now be a directory named Amberdocker.
. Move the AmberTools18, Amber18 and VNC viewer files to the Amberdocker directory.
. Build the Docker image (expect about an hour of wait time). 
+ 
 docker build . -t amber18:cpu
+


=== Run the Docker Container
. Get the path of the Amberdocker directory in the terimal.
+
 pwd
+
. Run the Docker container with the path from the previous step in place of {SharedFolder}.
+
 docker run --rm -p 5901:5901 -p 6901:6901 -v {SharedFolder}:/data --user 0 amber18:cpu
+


=== Connect to Container
. Open the VNC viewer.
+ 
* For Macs this should be in your applications folder. 
+
. Access the container (password: `vncpassword`).
+
* Via the VNC application: 127.0.0.1:5901

* Via the web: http://127.0.0.1:6901/vnc.html


